### ISSUE TITLE
lein deps fails

### ISSUE THREAD

**Issue by oemmerson** [NathanWilliams/anvil-view#1]
$ lein deps
Could not find artifact anvil-clj:anvil-clj:jar:0.1.0-SNAPSHOT in clojars (https://clojars.org/repo/)
Could not find artifact clj-ns-browser:clj-ns-browser:jar:1.3.2-SNAPSHOT-LOCAL in central (https://repo1.maven.org/maven2/)
Could not find artifact clj-ns-browser:clj-ns-browser:jar:1.3.2-SNAPSHOT-LOCAL in clojars (https://clojars.org/repo/)

**Comment by nonfctr** [comment]
Thanks Nathan for all of the hard work. I am trying to learn from you. I have the same issue when I tried to install this project using IntelliJ.

**Comment by NathanWilliams** [comment]
I'm sorry ode79, I never got a notification this issue was raised initially (only since nonfctr commented).
I'll look into it and see what I can do (it has been a while).

**Comment by NathanWilliams** [comment]
Ok, the problem was I forgot to document a few steps it seems (the problem with only testing on the dev machine).

First, there are two problems here:
clj-ns-browser:clj-ns-browser

I'm not sure why this can't be found now, I probably still have it in my local maven repo, which is why I don't get errors.
It isn't critical (only useful for development & maybe debugging in a repl.

To fix this, edit the project.clj, and remove this part:
[clj-ns-browser "1.3.2-SNAPSHOT-LOCAL"]

As for the missing anvil-clj, this is another project from my blog, but I forgot to document that you need to install it to your local repo first.

So to fix it:
Go clone this repo:
https://github.com/NathanWilliams/anvil-clj

after cloning change into the directory and run:
lein install

This will build anvil-clj into your local maven repo (where lein gets / installs dependancies).

Let me know if that works for you or not.
